// Auto-generated by arduino-build-daemon
#include <Arduino.h>
#line 1 "sample.ino"
#define USE_TIMER3_ISR
#include "mono_con.h"

const int led[3] = { B110, B101, B011 };
int idx = 0;

word tc;

ISR(TIMER3_COMPA_vect) {
	tc++;
}

void setup() {
	config_init();
	serial_init();
}

void loop() {
	if (tc > 1000) {
		tc = 0;
		lm.color.GBR = led[idx];
		if (++idx > 2) idx = 0;
	}
	led_stepmotor(lm.b8);
}
